version: '3'

services:
  mysql:
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_HOST=${DB_HOST:-127.0.0.1}
      - MYSQL_PORT=${DB_PORT:-3306}
      - MYSQL_DATABASE=${DB_DATABASE:-dev_test}
      - MYSQL_USER=${DB_USERNAME:-dev_test}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-secret}
    ports:
      - ${MYSQL_PORT:-33306}:3306

  client:
    build:
      context: ./
      dockerfile: docker/client/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports:
      - ${DEV_SERVER_PORT:-8081}:${DEV_SERVER_PORT:-8081}
    environment:
      - APP_ENV=${APP_ENV:-production}
    command: ./bin/client.sh

  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/vendor
    depends_on:
      - client
      - mysql

  nginx:
    image: 'nginx:latest'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT:-8080}:80
    depends_on:
      - app
